### ISSUE TITLE
example URL is 404

### ISSUE THREAD

**Issue by JBlond** [jkup/listify#3]
The example URL http://jonkuperman.com/listify give a 404 error

**Comment by jkup** [comment]
so sorry! I've been moving my personal site to github and a few pages like the example got lost in the shuffle. I'll have it fixed by tonight! See issue:
https://github.com/jkup/jkup.github.io/issues/5

**Comment by jkup** [comment]
took two days instead :/ but should be all good now!

**Comment by JBlond** [comment]
Thanks!
